"""
Report Templates for Policy Drafter System
Strategy& PWC - AI-Powered Policy Drafting Agent

Contains all template strings used for generating final policy reports.
"""

from datetime import datetime

class ReportTemplates:
    """Templates for generating final policy reports."""
    
    DRAFTING_CONTEXT_TEMPLATE = """
ORIGINAL POLICY REQUEST: {original_query}

ELABORATION FRAMEWORK:
{elaboration}

RESEARCH FINDINGS:
{research_content}

AVAILABLE CITATIONS:
{formatted_citations}
"""
    
    DEEP_RESEARCH_REPORT_TEMPLATE = """# Deep Research Analysis Report
*Generated by Strategy& PWC AI Policy Drafting System - Research Phase*

**Generated on:** {timestamp}
**Original Request:** {original_query}

---

## 🔍 Comprehensive Research Findings

*The following research was conducted to support policy drafting, covering international best practices, regulatory frameworks, implementation case studies, and stakeholder analysis.*

### Research Methodology
- **Citations Found:** {citations_count}
- **Research Domains:** International benchmarks, regulatory frameworks, implementation strategies, risk assessment
- **Geographic Coverage:** Global comparative analysis with regional specificity

---

## 📊 Research Content

{research_content}

---

## 📚 Research Citations and Sources

{citations_section}

---

*This research report provides the foundational evidence for policy development. All findings should be validated and supplemented with additional domain-specific research as needed.*

**Strategy& PWC - AI Policy Drafting System**
"""

    POLICY_DOCUMENT_REPORT_TEMPLATE = """# Policy Document
*Generated by Strategy& PWC AI Policy Drafting System - Policy Phase*

**Generated on:** {timestamp}
**Original Request:** {original_query}

---

## Executive Summary

This document presents a comprehensive policy framework developed through AI-powered analysis, incorporating global best practices, extensive research, and strategic recommendations suitable for government and organizational implementation.

---

## 📄 Complete Policy Document

{policy_document}

---

*This policy document was generated using advanced AI research and policy drafting capabilities. All recommendations should be reviewed by subject matter experts and legal counsel before implementation.*

**Strategy& PWC - AI Policy Drafting System**
"""

    SIMULATION_REPORT_TEMPLATE = """# Policy Implementation Simulation Report
*Generated by Strategy& PWC AI Policy Drafting System - Simulation Phase*

**Generated on:** {timestamp}

---

## Executive Summary

This simulation report presents comprehensive scenario analysis for the proposed policy implementation, examining multiple pathways including best-case outcomes, likely challenges, potential resistance, and resource constraints. Each scenario provides detailed implementation roadmaps, risk assessments, and strategic recommendations.

### Key Simulation Insights
- **Scenarios Analyzed:** 5 comprehensive implementation scenarios
- **Analysis Framework:** Multi-dimensional risk and opportunity assessment
- **Strategic Focus:** Implementation planning, stakeholder dynamics, resource optimization

---

## 🎯 Comprehensive Implementation Scenarios

*The following scenarios explore various implementation pathways, challenges, and outcomes to support strategic decision-making and risk management.*

### Simulation Methodology
- **Scenario Planning**: Best-case, most likely, worst-case, resistance, and resource constraint scenarios
- **Analysis Dimensions**: Political, economic, social, operational, and stakeholder perspectives
- **Strategic Framework**: Implementation phases, risk factors, mitigation strategies, and success metrics

---

## 🔮 Detailed Scenario Simulations

{simulation_results}

---

*This simulation analysis provides strategic insights for policy implementation. Scenarios should be regularly updated as conditions change, and contingency plans should be developed for each major risk factor identified.*

**Strategy& PWC - AI Policy Drafting System**
"""

    DATA_ANALYTICS_REPORT_TEMPLATE = """# Data Analytics Policy Report
*Generated by Strategy& PWC AI Policy Drafting System - Data Analytics Phase*

**Generated on:** {timestamp}
**Original Request:** {original_query}

---

## Executive Summary

This comprehensive data analytics report presents quantitative insights and visual analysis supporting the proposed policy framework. The report leverages evidence-based analysis, international benchmarks, and statistical modeling to provide decision-makers with actionable intelligence.

### Key Analytics Insights
- **Data-Driven Analysis:** Comprehensive metrics and statistical evaluation
- **Evidence-Based Recommendations:** All insights supported by credible data sources and statistical analysis

---

## 📊 Comprehensive Data Analytics Report

*The following analysis presents policy insights through visual data formats, statistical modeling, and quantitative assessments designed for executive decision-making.*

### Analytics Methodology
- **Data Sources:** Government statistics, peer-reviewed research, international organizations (UN, World Bank, OECD)
- **Analytical Framework:** Quantitative policy analysis with visual data presentation
- **Quality Standards:** High-trust sources with credible methodologies and transparent data collection

---

## 📈 Data-Driven Policy Analysis

{analytics_report}

---

*This data analytics report provides quantitative foundation for policy implementation decisions. All data points are sourced from credible institutions and should be regularly updated to maintain accuracy and relevance.*

**Strategy& PWC - AI Policy Drafting System**
"""
