"""
Chart Analytics Agent - LLM-Driven Dynamic Visualization Extraction
Extracts 8-12 self-describing visualizations from policy markdown documents
All titles, subtitles, insights, and data structures generated by LLM
Frontend renders generically with zero hardcoded logic
"""

from clients.openai_client import get_openai_client
from config.app_config import PolicyDrafterConfig
import json


CHART_EXTRACTION_PROMPT_TEMPLATE = """You are a data visualization specialist analyzing a policy analytics report. Your task is to identify and extract 8-12 visualizations that best represent the quantitative data in this markdown document.

For EACH visualization:
1. Choose the most appropriate chart type
2. Generate a clear, descriptive title (max 60 chars)
3. Write a contextual subtitle explaining what's shown (max 120 chars)
4. Extract a key insight highlighting the most important finding (1-2 sentences, max 200 chars)
5. Structure the data in Recharts-compatible format
6. Add chart-specific configuration if needed

OUTPUT SCHEMA (strict JSON, no markdown, no explanations):
{{
  "visualizations": [
    {{
      "id": "string (unique identifier, e.g., 'viz_1', 'viz_2')",
      "type": "kpi-cards" | "radar" | "bubble" | "bar-comparison" | "timeline" | "risk-matrix" | "waterfall" | "sankey" | "heatmap" | "treemap" | "area-trend" | "fan-chart",
      "title": "string (LLM-generated, descriptive, max 60 chars)",
      "subtitle": "string (LLM-generated, provides context, max 120 chars)",
      "insight": "string (LLM-generated, key finding, 1-2 sentences, max 200 chars)",
      "data": {{
        // Chart-type-specific Recharts-compatible data structure (see schemas below)
      }},
      "config": {{
        // Optional chart-specific configuration
      }},
      "metadata": {{
        "dataSource": "string (which report section, e.g., 'Financial Analysis Dashboard')",
        "confidence": "low" | "medium" | "high"
      }}
    }}
  ]
}}

CHART TYPE SCHEMAS & SELECTION GUIDE:

1. **kpi-cards**: Executive KPI dashboard
   When to use: Executive summary tables with 5-8 critical metrics showing current/target/gap
   Data structure:
   {{
     "metrics": [
       {{
         "label": "string (metric name, max 50 chars)",
         "current": "string (formatted value, e.g., '47%', '$120M')",
         "target": "string (formatted target, e.g., '60% by 2027')",
         "gap": number (numeric gap value, negative if below target),
         "trend": "up" | "down" | "stable",
         "color": "mint" | "blush" | "sky" | "cream"
       }}
     ]
   }}
   Color guide: mint=positive/government, blush=risk/negative, sky=comparison, cream=financial

2. **radar**: Multi-dimensional comparison
   When to use: Benchmark tables comparing countries/models across 5-7 dimensions
   Data structure:
   {{
     "dimensions": ["string (dimension name, e.g., 'Success Rate', 'Cost Efficiency')"],
     "entities": [
       {{
         "name": "string (entity name, e.g., 'UAE ICV', 'Canada ITB')",
         "scores": {{
           "dimension_name": number (0-100 normalized score)
         }}
       }}
     ]
   }}

3. **bubble**: Stakeholder/entity positioning
   When to use: Stakeholder tables with impact/support/population/influence dimensions
   Data structure:
   {{
     "xAxis": {{"label": "string", "min": number, "max": number}},
     "yAxis": {{"label": "string", "min": number, "max": number}},
     "bubbles": [
       {{
         "name": "string (stakeholder/entity name)",
         "x": number (X-axis value, typically support level 0-100),
         "y": number (Y-axis value, typically impact 0-10),
         "size": number (bubble size, typically population count),
         "color": "high" | "medium" | "low" (influence level)
       }}
     ]
   }}

4. **bar-comparison**: Current vs target metrics
   When to use: Performance tables with numeric current/target comparisons
   Data structure:
   {{
     "metrics": [
       {{
         "name": "string (metric name)",
         "current": number (numeric value only),
         "target": number (numeric value only),
         "unit": "%" | "$M" | "score" | "other"
       }}
     ]
   }}

5. **timeline**: Phased implementation roadmap
   When to use: Implementation phase tables with durations, milestones, dependencies
   Data structure:
   {{
     "phases": [
       {{
         "name": "string (phase name)",
         "start": "string (YYYY-MM format)",
         "end": "string (YYYY-MM format)",
         "duration": "string (human-readable, e.g., '12-18 months')",
         "milestones": ["string (milestone descriptions)"],
         "cost": number (in millions USD),
         "risk": "low" | "medium" | "high",
         "dependencies": ["string (prerequisite phase names)"]
       }}
     ]
   }}

6. **risk-matrix**: Risk probability × impact analysis
   When to use: Risk assessment tables with probability/impact/mitigation
   Data structure:
   {{
     "risks": [
       {{
         "name": "string (risk name, max 50 chars)",
         "probability": number (0-100),
         "impact": number (0-100),
         "severity": number (0-100, calculated as probability × impact / 100),
         "mitigation": "string (brief mitigation strategy, max 100 chars)"
       }}
     ]
   }}

7. **waterfall**: Year-over-year financial accumulation
   When to use: 5-year cost-benefit tables showing NPV/ROI accumulation
   Data structure:
   {{
     "periods": [
       {{
         "name": "string (period name, e.g., 'Baseline', 'Year 1')",
         "value": number (change from previous period, can be negative),
         "cumulative": number (cumulative total),
         "breakeven": boolean (optional, true if this period achieves break-even)
       }}
     ]
   }}

8. **sankey**: Budget/resource allocation flow
   When to use: Resource requirement matrices showing hierarchical fund flows
   Data structure:
   {{
     "nodes": [
       {{"id": "string (unique node ID)", "name": "string (display name)"}}
     ],
     "links": [
       {{
         "source": "string (source node ID)",
         "target": "string (target node ID)",
         "value": number (flow amount in millions USD)
       }}
     ]
   }}

9. **heatmap**: Matrix of adoption/intensity
   When to use: Cross-reference tables (country × instrument, region × metric)
   Data structure:
   {{
     "rows": ["string (row labels, e.g., country names)"],
     "columns": ["string (column labels, e.g., policy instruments)"],
     "cells": [
       {{
         "row": "string (matches row label)",
         "column": "string (matches column label)",
         "value": number (intensity, 0-100 scale)
       }}
     ]
   }}

10. **treemap**: Hierarchical budget allocation
    When to use: Nested budget categories (Category → Subcategory → Amount)
    Data structure:
    {{
      "children": [
        {{
          "name": "string (category name)",
          "value": number (amount in millions USD)",
          "children": [
            {{"name": "string (subcategory)", "value": number}}
          ]
        }}
      ]
    }}

11. **area-trend**: Time-series projections
    When to use: Year-over-year financial trajectories (ROI, investment, returns)
    Data structure:
    {{
      "series": [
        {{
          "name": "string (series name, e.g., 'ROI', 'Investment')",
          "values": [
            {{"year": number (1-5), "value": number}}
          ]
        }}
      ]
    }}

12. **fan-chart**: Scenario projections with uncertainty
    When to use: Probabilistic projections with best/likely/worst cases
    Data structure:
    {{
      "years": [number (1-5)],
      "scenarios": {{
        "best": [number (values for each year)],
        "likely": [number (values for each year)],
        "worst": [number (values for each year)]
      }}
    }}

EXTRACTION RULES:
1. **Extract 8-12 visualizations** based on report richness (not all types will apply to every report)
2. **Prioritize high-value visualizations**: Focus on data that drives decision-making
3. **Normalize all data**:
   - Scores: 0-100 scale
   - Currency: millions USD (convert SAR/AED/QAR using approximate rates)
   - Dates: YYYY-MM format
   - Qualitative levels: Low=25, Medium=50, High=75, Very High=90
4. **Generate descriptive titles**: Answer "What is being compared/shown?"
5. **Generate actionable insights**: Answer "What's the most important finding?"
6. **Validate data completeness**: Skip visualizations if insufficient data exists
7. **Order by importance**: Place highest-impact visualizations first

DATA EXTRACTION PRIORITIES:
- **Always extract if present**: Executive metrics (kpi-cards), Financial projections (waterfall/area-trend), Risk assessment (risk-matrix)
- **High value if present**: Stakeholder analysis (bubble), International benchmarks (radar/heatmap), Timeline (timeline/Gantt)
- **Medium value if present**: Resource allocation (treemap/sankey), Scenario analysis (fan-chart)
- **Extract only if data-rich**: Performance bars (bar-comparison) - skip if fewer than 5 metrics

MARKDOWN DOCUMENT:
{markdown_content}

Output ONLY valid JSON with the exact structure above. No additional text, no markdown formatting, no code blocks.
"""


def extract_chart_data(markdown_content: str) -> dict:
    """
    Uses LLM to extract 8-12 self-describing visualizations from markdown policy document.

    This function leverages GPT-5 with reasoning to:
    1. Identify the most valuable data visualizations in the report
    2. Generate titles, subtitles, and insights for each visualization
    3. Extract and normalize data into Recharts-compatible structures
    4. Return a fully self-describing JSON that frontend can render generically

    Args:
        markdown_content: Raw markdown text from analytics report

    Returns:
        Dict with 'visualizations' array containing 8-12 self-describing chart objects
        Each visualization has: id, type, title, subtitle, insight, data, config, metadata
    """
    print("📊 Extracting dynamic visualizations via LLM...")
    print(f"📄 Input markdown length: {len(markdown_content)} characters")

    client = get_openai_client()

    system_msg = """You are an expert data visualization specialist. You analyze policy documents and intelligently extract the most valuable visualizations.

Key principles:
1. Be selective - extract 8-12 high-impact visualizations, not everything
2. Generate descriptive titles that explain what's being shown
3. Write insights that highlight the key finding in each visualization
4. Normalize all data to consistent scales and units
5. Output ONLY valid JSON, no markdown, no explanations"""

    user_msg = CHART_EXTRACTION_PROMPT_TEMPLATE.format(
        markdown_content=markdown_content
    )

    print(f"🤖 Calling LLM with GPT-5 + medium reasoning effort...")
    print(f"   Analyzing report structure and identifying optimal visualizations...")

    json_response = client.responses_create_and_wait(
        model=PolicyDrafterConfig.GPT_5,
        system_message=system_msg,
        user_message=user_msg,
        reasoning={"effort": "medium"}
    )

    print(f"✅ LLM response received: {len(json_response)} characters")

    # Parse JSON response
    try:
        # Clean response - remove markdown code blocks if present
        cleaned_response = json_response.strip()
        if cleaned_response.startswith("```"):
            lines = cleaned_response.split('\n')
            cleaned_response = '\n'.join(lines[1:-1]) if len(lines) > 2 else cleaned_response
            cleaned_response = cleaned_response.replace("```json", "").replace("```", "")

        chart_data = json.loads(cleaned_response)
        print(f"✅ JSON parsed successfully")

        # Validate structure
        if "visualizations" not in chart_data:
            print(f"❌ Error: 'visualizations' key not found in response")
            raise ValueError("Invalid response structure - missing 'visualizations' array")

        visualizations = chart_data["visualizations"]
        print(f"📊 Extracted {len(visualizations)} visualizations:")

        # Log each visualization
        for i, viz in enumerate(visualizations, 1):
            viz_type = viz.get("type", "unknown")
            viz_title = viz.get("title", "Untitled")
            print(f"   {i}. [{viz_type}] {viz_title}")

        # Validate each visualization has required fields
        required_fields = ["id", "type", "title", "data"]
        for viz in visualizations:
            for field in required_fields:
                if field not in viz:
                    print(f"⚠️  Warning: Visualization missing required field '{field}'")

        return chart_data

    except json.JSONDecodeError as e:
        print(f"❌ Error parsing JSON response: {e}")
        print(f"Response preview: {json_response[:500]}...")
        raise
    except Exception as e:
        print(f"❌ Error processing LLM response: {e}")
        raise


if __name__ == "__main__":
    # Test extraction with sample markdown
    test_markdown = """
    # Test Analytics Report

    ## Executive Summary
    | Metric | Current | Target | Gap |
    |--------|---------|--------|-----|
    | LC Rate | 47% | 70% | -23 pp |
    | IKTVA | 67% | 70% | -3 pp |

    ## 5-Year Financial Projection
    | Year | Investment | Returns | ROI |
    |------|-----------|---------|-----|
    | 1 | $120M | $60M | -58% |
    | 2 | $110M | $140M | -8% |
    | 3 | $90M | $180M | +12% |

    ## International Benchmarking
    UAE: 88/100 (ICV program)
    Norway: 85/100 (Petroleum policy)
    Canada: 82/100 (ITB benefits)

    ## Risk Assessment
    - WTO compliance: Probability 30%, Impact High
    - Cost inflation: Probability 50%, Impact Medium
    """

    result = extract_chart_data(test_markdown)
    print("\n📋 Test extraction result:")
    print(json.dumps(result, indent=2))
