"""
Impact Visualization Agent - LLM-Driven Visualization Extraction
Extracts 5-8 self-describing visualizations from impact analysis reports
All titles, subtitles, insights, and data structures generated by LLM
Frontend renders generically with zero hardcoded logic
"""

from clients.openai_client import get_openai_client
from config.app_config import PolicyDrafterConfig
from agents.impact_analysis.mermaid_validator import validate_mermaid_syntax, fix_mermaid_diagram
import json
from typing import Dict, List


IMPACT_VIZ_EXTRACTION_PROMPT_TEMPLATE = """You are a data visualization specialist analyzing an impact analysis report with citations. Your task is to identify and extract 5-8 visualizations that best represent the findings.

For EACH visualization:
1. Choose the most appropriate chart type
2. Generate a clear, descriptive title (max 60 chars)
3. Write a contextual subtitle explaining what's shown (max 120 chars)
4. Extract a key insight highlighting the most important finding (1-2 sentences, max 200 chars)
5. Structure the data in chart-compatible format
6. Add chart-specific configuration if needed

OUTPUT SCHEMA (strict JSON, no markdown, no explanations):
{{
  "visualizations": [
    {{
      "id": "string (unique identifier, e.g., 'impact_kpis', 'multiplier_range')",
      "type": "kpi-cards" | "citation-cards" | "bar-comparison" | "timeline-chart" | "mermaid-diagram" | "radar" | "pie-chart" | "data-table",
      "title": "string (LLM-generated, descriptive, max 60 chars)",
      "subtitle": "string (LLM-generated, provides context, max 120 chars)",
      "insight": "string (LLM-generated, key finding, 1-2 sentences, max 200 chars)",
      "data": {{
        // Chart-type-specific data structure (see schemas below)
      }},
      "config": {{
        // Optional chart-specific configuration
      }},
      "metadata": {{
        "confidence": "low" | "medium" | "high",
        "dataSource": "string (which section this came from)"
      }}
    }}
  ]
}}

CHART TYPE SCHEMAS & SELECTION GUIDE:

1. **kpi-cards**: Executive KPI dashboard
   When to use: ALWAYS create this first - summary of key impact metrics
   Data structure:
   {{
     "metrics": [
       {{
         "label": "string (metric name, max 50 chars)",
         "value": "string (formatted value, e.g., '2.3%', '8.5/10')",
         "subtitle": "string (brief context, max 80 chars)",
         "trend": "up" | "down" | "stable" | "neutral",
         "color": "emerald" | "rose" | "sky" | "amber",
         "icon": "multiplier" | "quality" | "citations" | "confidence"
       }}
     ]
   }}
   Typical metrics: Weighted avg multiplier, evidence quality score, citation count, confidence level

2. **citation-cards**: Rich citation gallery
   When to use: ALWAYS create this - showcase the academic sources
   Data structure:
   {{
     "citations": [
       {{
         "title": "string",
         "publisher": "string",
         "year": "string",
         "url": "string",
         "doi": "string (optional)",
         "quality_score": "high" | "medium" | "low",
         "source_tier": "string (e.g., 'peer_reviewed_econometric')",
         "key_finding": "string",
         "methodology": "string",
         "multiplier": "string (optional)",
         "badge_color": "emerald" | "amber" | "rose"
       }}
     ]
   }}

3. **bar-comparison**: Impact multiplier range comparison
   When to use: If report has multiplier estimates showing min/max/average
   Data structure:
   {{
     "bars": [
       {{
         "name": "string (e.g., 'Minimum Effect', 'Weighted Average', 'Maximum Effect')",
         "value": number (the multiplier value),
         "unit": "%" | "x" | "points",
         "citation": number (optional - citation index),
         "color": "emerald" | "sky" | "amber"
       }}
     ],
     "yAxisLabel": "Impact Multiplier (%)",
     "showValues": true
   }}

4. **timeline-chart**: Time-differentiated effects
   When to use: If report mentions immediate/short-term/long-term effects
   Data structure:
   {{
     "periods": [
       {{
         "name": "string (e.g., 'Immediate (0-1 year)', 'Short-term (1-3 years)')",
         "multiplier": number,
         "description": "string (brief explanation, max 100 chars)",
         "citations": [number] (citation indices)
       }}
     ]
   }}

5. **mermaid-diagram**: Causal pathway visualization
   When to use: If report section "Causal Mechanisms" or "Causal Pathways" exists
   Data structure:
   {{
     "diagram": "string (valid Mermaid syntax - graph TD or LR format)",
     "description": "string (what the diagram shows, max 150 chars)"
   }}
   Rules for Mermaid:
   - Use simple syntax: graph TD or graph LR
   - Node format: A[Label], B(Label), C{{Label}}
   - Arrow format: --> or -.->
   - Keep to 8-12 nodes maximum
   - Example: "graph TD\\n  A[Policy X] --> B[Mechanism 1]\\n  B --> C[Outcome Y]\\n  A --> D[Mechanism 2]\\n  D --> C"

6. **radar**: Evidence quality assessment
   When to use: If report has "Evidence Quality" or "Methodological Assessment" section
   Data structure:
   {{
     "dimensions": ["string (dimension names, e.g., 'Internal Validity', 'Sample Size')"],
     "score": number (0-100 overall score),
     "dimensionScores": {{
       "dimension_name": number (0-100)
     }},
     "interpretation": "string (what the scores mean, max 150 chars)"
   }}

7. **pie-chart**: Methodology distribution
   When to use: If multiple methodologies used across citations
   Data structure:
   {{
     "slices": [
       {{
         "method": "string (methodology name, e.g., 'RCT', 'DiD', 'IV')",
         "count": number (number of studies),
         "percentage": number (0-100),
         "quality": "high" | "medium" | "low",
         "color": "emerald" | "sky" | "amber" | "rose"
       }}
     ],
     "total": number (total citations)
   }}

8. **data-table**: Structured data comparison
   When to use: If report has comparative tables (e.g., study comparison, context-specific effects)
   Data structure:
   {{
     "columns": ["string (column headers)"],
     "rows": [
       {{
         "column_name": "string | number"
       }}
     ],
     "sortable": boolean,
     "highlightColumn": string (optional - which column to highlight)
   }}

EXTRACTION RULES:
1. **Always extract**: kpi-cards (executive metrics) and citation-cards (source gallery)
2. **Extract if data exists**: bar-comparison (multipliers), timeline-chart (time effects), mermaid-diagram (causal pathways)
3. **Extract if rich data**: radar (quality assessment), pie-chart (methodology breakdown), data-table (comparisons)
4. **Total visualizations**: Aim for 5-8 based on report richness
5. **Order by importance**: KPIs first, then citations, then analytical charts
6. **Data extraction**: Pull numbers directly from report text and citation data
7. **Mermaid diagrams**: Extract from ASCII diagrams or create from text descriptions of causal pathways
8. **Color coding**:
   - emerald = positive/high quality/strong evidence
   - amber = medium/warning
   - rose = low/risk/weak evidence
   - sky = neutral/comparison

DATA EXTRACTION PRIORITIES:
- **Executive Summary**: Extract overall multiplier, confidence level, evidence quality
- **Citations**: Map ALL citations to citation-cards with quality badges
- **Section 3 (Impact Multipliers)**: Extract min/max/average for bar-comparison and time periods for timeline
- **Section 2 (Causal Mechanisms)**: Convert pathway descriptions or ASCII diagrams to Mermaid syntax
- **Section 4 (Evidence Quality)**: Extract quality scores for radar chart
- **Methodology mentions**: Count methodology types for pie chart

MARKDOWN REPORT:
{markdown_content}

CITATIONS DATA (JSON):
{citations_json}

Output ONLY valid JSON with the exact structure above. No additional text, no markdown formatting, no code blocks.
"""


def extract_impact_visualizations(markdown_content: str, citations: List[Dict]) -> Dict:
    """
    Uses LLM to extract 5-8 self-describing visualizations from impact analysis report.

    This function leverages GPT-5 with reasoning to:
    1. Identify the most valuable visualizations for the impact report
    2. Generate titles, subtitles, and insights for each visualization
    3. Extract and structure data in chart-compatible formats
    4. Create Mermaid diagrams from causal pathway descriptions
    5. Return a fully self-describing JSON for generic frontend rendering

    Args:
        markdown_content: Impact analysis markdown text
        citations: List of citation dictionaries with metadata

    Returns:
        Dict with 'visualizations' array containing 5-8 self-describing chart objects
        Each visualization has: id, type, title, subtitle, insight, data, config, metadata
    """
    print("📊 Extracting impact visualizations via LLM...")
    print(f"📄 Input markdown length: {len(markdown_content)} characters")
    print(f"📚 Citations count: {len(citations)}")

    client = get_openai_client()

    # Prepare citations as JSON string for LLM
    citations_json = json.dumps(citations, indent=2, ensure_ascii=False)

    system_msg = """You are an expert data visualization specialist for impact analysis reports. You analyze academic impact studies and intelligently extract the most valuable visualizations.

Key principles:
1. Always extract KPI cards and citation gallery first
2. Generate descriptive titles that explain what's being compared/shown
3. Write insights that highlight key findings in plain language
4. Extract numbers precisely as stated in the report
5. Create valid Mermaid diagrams from pathway descriptions
6. Output ONLY valid JSON, no markdown, no explanations"""

    user_msg = IMPACT_VIZ_EXTRACTION_PROMPT_TEMPLATE.format(
        markdown_content=markdown_content,
        citations_json=citations_json
    )

    print(f"🤖 Calling LLM with GPT-5 + medium reasoning effort...")
    print(f"   Analyzing report structure and identifying optimal visualizations...")

    json_response = client.responses_create_and_wait(
        model=PolicyDrafterConfig.GPT_5,
        system_message=system_msg,
        user_message=user_msg,
        reasoning={"effort": "medium"}
    )

    print(f"✅ LLM response received: {len(json_response)} characters")

    # Parse JSON response
    try:
        # Clean response - remove markdown code blocks if present
        cleaned_response = json_response.strip()
        if cleaned_response.startswith("```"):
            lines = cleaned_response.split('\n')
            cleaned_response = '\n'.join(lines[1:-1]) if len(lines) > 2 else cleaned_response
            cleaned_response = cleaned_response.replace("```json", "").replace("```", "")

        viz_data = json.loads(cleaned_response)
        print(f"✅ JSON parsed successfully")

        # Validate structure
        if "visualizations" not in viz_data:
            print(f"❌ Error: 'visualizations' key not found in response")
            raise ValueError("Invalid response structure - missing 'visualizations' array")

        visualizations = viz_data["visualizations"]
        print(f"📊 Extracted {len(visualizations)} visualizations:")

        # Log each visualization
        for i, viz in enumerate(visualizations, 1):
            viz_type = viz.get("type", "unknown")
            viz_title = viz.get("title", "Untitled")
            print(f"   {i}. [{viz_type}] {viz_title}")

        # Validate each visualization has required fields
        required_fields = ["id", "type", "title", "data"]
        for viz in visualizations:
            for field in required_fields:
                if field not in viz:
                    print(f"⚠️  Warning: Visualization '{viz.get('id', 'unknown')}' missing required field '{field}'")

        # Validate and fix Mermaid diagrams
        print(f"\n🔍 Validating Mermaid diagrams...")
        for viz in visualizations:
            if viz.get("type") == "mermaid-diagram":
                diagram = viz.get("data", {}).get("diagram", "")

                if not diagram:
                    print(f"⚠️  Mermaid diagram '{viz.get('id')}' has no content")
                    continue

                # Validate syntax
                is_valid, error = validate_mermaid_syntax(diagram)

                if is_valid:
                    print(f"✅ Mermaid diagram '{viz.get('id')}' is valid")
                else:
                    print(f"⚠️  Mermaid diagram '{viz.get('id')}' has invalid syntax: {error}")
                    print(f"   Attempting to fix...")

                    # Get context for better fixing
                    context = f"{viz.get('title', '')}. {viz.get('subtitle', '')}"

                    # Fix the diagram
                    fixed_diagram = fix_mermaid_diagram(diagram, context)

                    # Validate the fix
                    is_valid_now, error_now = validate_mermaid_syntax(fixed_diagram)

                    if is_valid_now:
                        # Update with fixed version
                        viz["data"]["diagram"] = fixed_diagram
                        print(f"✅ Mermaid diagram '{viz.get('id')}' corrected and validated")
                    else:
                        print(f"❌ Could not fix diagram '{viz.get('id')}': {error_now}")
                        print(f"   Frontend will use text fallback")

        return viz_data

    except json.JSONDecodeError as e:
        print(f"❌ Error parsing JSON response: {e}")
        print(f"Response preview: {json_response[:500]}...")
        raise
    except Exception as e:
        print(f"❌ Error processing LLM response: {e}")
        raise


